---
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: mern-frontend
    networks:
      - mern-network
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    container_name: mern_backend
    networks:
      - mern-network
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mern_db
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db
networks:
  mern-network:
    driver: bridge
volumes:
  mongo-data:
...